name: polla
description: Polling App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  google_sign_in: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: ArimaMadurai
      fonts:
        - asset: fonts/ArimaMadurai-Black.ttf
          weight: 900

  assets:
    - images/
